name: Java11

on:
  push:
    paths:
      - '*/*/java11.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */3 * * *'
jobs:
  java11:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2016]
        update: [x, 7, 6, 5, 4, 3, 2, 1]
      fail-fast: false
      max-parallel: 5
    name: JDK 11.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.${{ matrix.update }}
    - name: java -version
      run: java -version
