name: Java15

on:
  push:
    paths:
      - '*/*/java15.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *'
      
jobs:
  java13:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2016]
        update: [15.0.0-ea, 15.0.0-ea.2, ">15.0.0-ea"]
      fail-fast: false
      max-parallel: 5=6
    name: JDK ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: giltene/setup-java@master
      with:
        java-version: ${{ matrix.update }}
    - name: java -version
      run: java -version
