name: ZingAndZuluMatrixExample

on:
  push:
    paths:
      - '.github/workflows/ZingAndZuluMatrixExample.yml'

jobs:
  java:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        version: [8, 11]
        actions: [actions, zing-actions]
      fail-fast: false
      max-parallel: 7
    name: ${{ matrix.actions }} JDK ${{ matrix.version }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      run: echo "Setting up JDK using ${{ matrix.actions }}"
    - if: matrix.actions =='actions'
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}
    - if: matrix.actions =='zing-actions'
      uses: zing-actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}  
    - name: java -version
      run: java -version
